apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-web1
spec:
  rules:
  - host: web1.example.com
    http:
      paths:
      - path: /
        backend:
          serviceName: nginx-deploy-svc
          servicePort: 31240
