apiVersion: batch/v1
kind: Job
metadata:
  name: calc-pi
  namespace: default
spec:
  template:
    metadata:
      name: calc-pi
    spec:
      containers:
      - name: calc-pi
        image: perl
        command: ["perl","-Mbignum=bpi","-wle","print bpi(2000)"]
      restartPolicy: Never
  
