apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-rc-c
  namespace: default
  labels:
    app: nginx-rc-c
spec:
  replicas: 2
  selector:
    app: nginx-rc-c
  template:
    metadata:
      labels:
        app: nginx-rc-c
    spec:
      containers:
      - name: nginx-rc-c
        image: jinling/nginx:alpine0
  
