apiVersion: v1
kind: ReplicationController
metadata:
  creationTimestamp: "2019-09-16T02:05:15Z"
  generation: 1
  labels:
    run: nginx-rc-b
  name: nginx-rc-b
  namespace: default
  resourceVersion: "52260"
  selfLink: /api/v1/namespaces/default/replicationcontrollers/nginx-rc-b
  uid: 1a4d09d0-ce97-4de0-a3cb-e034d431df75
spec:
  replicas: 3
  selector:
    run: nginx-rc-b
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: nginx-rc-b
    spec:
      containers:
      - image: jinling/nginx:alpine0
        imagePullPolicy: IfNotPresent
        name: nginx-rc-b
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 3
  fullyLabeledReplicas: 3
  observedGeneration: 1
  readyReplicas: 3
  replicas: 3
