apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-deploy-a
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-deploy-a
  template:
    metadata:
      labels:
        app: nginx-deploy-a
    spec:
      containers:
      - name: nginx-deploy-a
        image: jinling/nginx:alpine0
  
