apiVersion: v1
kind: Pod
metadata:
  name: pod-b1
spec:
  containers:
  - name:  pod-b1-c1
    image: jinling/busybox:bbb
    volumeMounts:
    - name: cv1
      mountPath: /bbb
      readOnly: true
  volumes:
  - name: cv1
    configMap: 
     name: manyconf
