apiVersion: v1
kind: Pod
metadata:
  name: pod-ssl
spec:
  containers:
  - name: genereator-c
    image: jinling/fortune:env
    volumeMounts:
    - name: webcontents-v
      mountPath: /var/htdocs
    env:
    - name: SLEEP_INTERVAL
      valueFrom:
        configMapKeyRef:
          name: fortune-literal-5
          key: sleepinterval

  - name: web-ssl
    image: nginx:latest
    ports:
    - containerPort: 80
    - containerPort: 443
    volumeMounts:
    - name: webcontents-v
      mountPath: /usr/share/nginx/html
      readOnly: true
    - name: nginx-conf-v
      mountPath: /etc/nginx/conf.d/
      readOnly: true
    - name: nginx-cert-v
      mountPath: /etc/nginx/certs
      readOnly: true

  volumes:
  - name: webcontents-v
    emptyDir: {}
  - name: nginx-conf-v
    configMap:
      name: nginx-conf
      items:
      - key: nginx-config-https.conf
        path: https.conf 
  - name: nginx-cert-v
    secret:
      secretName: nginx-ssl
