---
apiVersion: v1
kind: Pod
metadata:
  name: pod1
spec:
  containers:
    - name: pod1-c1
      image: nginx:latest
      ports:
        - containerPort: 80
          name: "nginx-server"
      volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: vol1
  volumes:
    - name: vol1
      persistentVolumeClaim:
       claimName: pvc1
