apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2019-09-16T01:41:24Z"
  labels:
    run: podx
  name: podx
  namespace: default
  resourceVersion: "49657"
  selfLink: /api/v1/namespaces/default/pods/podx
  uid: c57f5dad-a7dd-405b-b746-4a08ac3cb7f1
spec:
  containers:
  - image: jinling/nginx:alpine0
    imagePullPolicy: IfNotPresent
    name: podx
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-m9z4j
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: wornode1.example.com
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: default-token-m9z4j
    secret:
      defaultMode: 420
      secretName: default-token-m9z4j
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2019-09-16T01:41:24Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2019-09-16T01:41:26Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2019-09-16T01:41:26Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2019-09-16T01:41:24Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://81efcd495778998b9112e8744e72de91839ca7090df59678cd8dcdc9a248684d
    image: jinling/nginx:alpine0
    imageID: docker-pullable://jinling/nginx@sha256:92930c13dfeda5f332dc4840f187e533ff8d0708d4e65455447690b53a460696
    lastState: {}
    name: podx
    ready: true
    restartCount: 0
    state:
      running:
        startedAt: "2019-09-16T01:41:25Z"
  hostIP: 192.168.0.101
  phase: Running
  podIP: 10.244.1.13
  qosClass: BestEffort
  startTime: "2019-09-16T01:41:24Z"
