---
apiVersion: v1
kind: Service
metadata:
  name: svc-1
spec:
  selector:
    app: webapp
  type: ClusterIP
  clusterIP: None
  ports:
  - port: 27017  
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: deploy-1
spec:
  selector:
    matchLabels:
      app: webapp
  replicas: 3
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: rs-svc-pod-c
        image: nginx:latest
        ports:
        - containerPort: 80
          protocol: TCP
        volumeMounts:
        - name: v10
          mountPath: /usr/share/nginx/html
      volumes:
      - name: v10
        persistentVolumeClaim:
          claimName: pvc10g
