---
apiVersion: v1
kind: Service
metadata:
  name: nginx-hl-svc
spec:
  selector:
    app: niginxtest
  type: ClusterIP
  clusterIP: None
  ports:
  - port: 27017  
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: stateful1
spec:
  selector:
    matchLabels:
      app: nginxtest
  serviceName: nginxsvc
  replicas: 3
  template:
    metadata:
      labels:
        app: nginxtest
    spec:
      containers:
      - name: nginxtest
        image: nginx:latest
        ports:
        - containerPort: 80
          protocol: TCP
        volumeMounts:
        - name: nfs-data
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
  - metadata:
      name: nfs-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "nfs"
      resources:
        requests:
          storage: 1Gi
