apiVersion: v1
kind: Pod
metadata:
  name: hostpath-pod
spec:
  containers:
  - name: hostpath-c
    image: nginx:latest
    volumeMounts:
    - name: host-vol
      mountPath: /usr/share/nginx/html
  volumes:
  - name: host-vol
    hostPath:
      path: /hostdir
