apiVersion: v1
kind: Pod
metadata:
  name: vol-emptydir
spec:
  containers:
  - name: webserver
    image: nginx:latest
    volumeMounts:
    - name: html-content
      mountPath: /usr/share/nginx/html
      readOnly: true    
    

  - name: content-generator
    image: jinling/fortune-gen:v1
    volumeMounts:
    - name: html-content
      mountPath: /www/html
  volumes:
  - name: html-content
    emptyDir: {}
