apiVersion: v1
kind: Pod
metadata:
  name: gitrepo-pod
spec:
  containers:
  - name: example-c
    image: nginx:latest
    volumeMounts:
    - name: jinlingtest-example
      mountPath: /usr/share/nginx/html
      readOnly: true
    ports:
    - containerPort: 80
      protocol: TCP
  volumes:
  - name: jinlingtest-example
    gitRepo:
      repository: https://github.com/JinlingTest/example.git
      revision: master
      directory: .
