apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: https://web5.example.com:31706
  name: rewrite
  namespace: default
spec:
  rules:
  - host: web.example.com
    http:
      paths:
      - backend:
          serviceName: nginx-deploy-svc5
          servicePort: 80
