apiVersion: v1
kind: Pod
metadata:
   name: weby

   labels:
     app: http
     creation_method: manual
     v1: abc 
spec: 
   containers:
    - image: jinling/nginx:alpine0
      name: weby
      ports:
        - containerPort: 80
          protocol: TCP
