apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2019-09-12T06:35:01Z"
  labels:
    run: yourweb
  name: yourweb
  namespace: default
  resourceVersion: "25846"
  selfLink: /api/v1/namespaces/default/pods/yourweb
  uid: 202cb3d8-e79a-4cd6-b07d-50fab08e22e2
spec:
  containers:
  - image: jinling/nginx:alpine0
    imagePullPolicy: IfNotPresent
    name: yourweb
    ports:
    - containerPort: 80
      protocol: TCP
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-m9z4j
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: wornode1.example.com
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: default-token-m9z4j
    secret:
      defaultMode: 420
      secretName: default-token-m9z4j
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2019-09-12T06:35:01Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2019-09-12T06:35:02Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2019-09-12T06:35:02Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2019-09-12T06:35:01Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://16c381794c9a77da1ad9c89e27c96596455967c748db3803c7a479cc7a4ff30c
    image: jinling/nginx:alpine0
    imageID: docker-pullable://jinling/nginx@sha256:92930c13dfeda5f332dc4840f187e533ff8d0708d4e65455447690b53a460696
    lastState: {}
    name: yourweb
    ready: true
    restartCount: 0
    state:
      running:
        startedAt: "2019-09-12T06:35:02Z"
  hostIP: 192.168.0.101
  phase: Running
  podIP: 10.244.1.7
  qosClass: BestEffort
  startTime: "2019-09-12T06:35:01Z"
