---
- hosts: 192.168.0.201
  remote_user: root
  tasks:
   - name: add user testuser1
     user:
      name: "{{ item.username }}"
      state: present
      group: "{{ item.groupname }}"
     loop:
#    with_items:
#     - testuser1
      - {username: 'testuser1', groupname: 'wheel' }
      - {username: 'testuser2', groupname: 'root' }
      - {username: 'testuser3', groupname: 'postfix' }

