---
- hosts: 192.168.0.201
  remote_user: root
  tasks:
   - name: add user testuser1
     user:
      name: "{{ item }}"
      state: present
      groups: "wheel"
#     loop:
     with_items: 
      - testuser1
      - testuser2
      - testuser3
#   - name: add user testuser1
#     user:
#      name: "testuser1"
#      state: present
#      groups: "wheel"
#
##   - name: add user testuser2
#     user:
#      name: "testuser2"
#      state: present
#      groups: "wheel"
