---
# This role will install MySQL and create db user and give permissions.
- name: A
  yum: 
   name: 'https://dev.mysql.com/get/mysql80-community-release-el7-3.noarch.rpm'
- name: B
  shell: 'yum-config-manager --disable mysql80-community'
- name: C
  shell: 'yum-config-manager --enable mysql56-community'

- name: Install Mysql package
  yum: name={{ item }} state=present
  with_items:
   - mysql-community-server
   - MySQL-python

- name: Configure SELinux to start mysql on any port
  seboolean: name=mysql_connect_any state=true persistent=yes
  when: sestatus.rc != 0

- name: Create Mysql configuration file
  template: src=my.cnf.j2 dest=/etc/my.cnf
  notify:
  - restart mysql

- name: Start Mysql Service
  service: name=mysqld state=started enabled=yes

- name: Create Application Database
  mysql_db: name={{ dbname }} state=present

- name: Create Application DB User
  mysql_user: name={{ dbuser }} password={{ upassword }} priv=*.*:ALL host='%' state=present
